apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4-rc-focal
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: dXNlcm5hbWUK
              # valueFrom:
              #   secretKeyRef:
              #     name: mongodb-secret
              #     key: mongodb-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: cGFzc3dvcmQK
              # valueFrom:
              # secretKeyRef:
              # name: mongodb-secret
              # key: mongodb-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
